version : '3.8'
services:
  ry-mysql:
    platform: linux/x86_64
    container_name: ry-mysql
    build:
      context: ./mysql
      dockerfile: dockerfile
    ports:
      - "3308:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    command: [
          'mysqld',
          '--innodb-buffer-pool-size=80M',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci',
          '--default-time-zone=+8:00',
          '--lower-case-table-names=1'
        ]
    environment:
      MYSQL_DATABASE: 'ry-vue'
      MYSQL_ROOT_PASSWORD: password
  ry-redis:
    container_name: ry-redis
    image: redis
    ports:
      - "6380:6379"
    restart: always
    volumes:
      - ./redis/conf/redis.conf:/home/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /home/redis/redis.conf
  ry-server:
    container_name: ry-server
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./upload:/home/uploadPath
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: always
    depends_on:
      - ry-redis
      - ry-mysql
    links:
      - ry-redis
      - ry-mysql
  ry-ui:
    container_name: ry-ui
    image: nginx
    ports:
      - "1024:80"
    restart: always
    volumes:
      - ./ui/logs:/var/log/nginx
      - ./ui/html/dist:/usr/share/nginx/html
      - ./ui/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./ui/conf.d:/etc/nginx/conf.d


